CREATE TABLE "COLL_DACOS_STATUS"
   (	"LINK_ID" VARCHAR2(8),
	"SEND_DT" VARCHAR2(14),
	"COMPANY_ID" VARCHAR2(5),
	"MEMBER_NM" VARCHAR2(30),
	"USER_ID" VARCHAR2(20),
	"WORK_ID" VARCHAR2(5),
	"WORK_RESULT_ID" VARCHAR2(5),
	"SERVICE_ID" VARCHAR2(50),
	"PROC_ST" VARCHAR2(5),
	"PROC_TX" VARCHAR2(50),
	"REG_DATE" DATE,
	"EULBU_NO" VARCHAR2(20)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

COMMENT ON TABLE AUTO.COLL_DACOS_STATUS IS '지그비 위치';
COMMENT ON COLUMN AUTO.COLL_DACOS_STATUS.LINK_ID IS '연계ID';
COMMENT ON COLUMN AUTO.COLL_DACOS_STATUS.SEND_DT IS '송/수신일자';
COMMENT ON COLUMN AUTO.COLL_DACOS_STATUS.COMPANY_ID IS '회사ID';
COMMENT ON COLUMN AUTO.COLL_DACOS_STATUS.MEMBER_NM IS '담당자명';
COMMENT ON COLUMN AUTO.COLL_DACOS_STATUS.USER_ID IS '회원ID';
COMMENT ON COLUMN AUTO.COLL_DACOS_STATUS.WORK_ID IS '업무ID';
COMMENT ON COLUMN AUTO.COLL_DACOS_STATUS.WORK_RESULT_ID IS '결과업무ID';
COMMENT ON COLUMN AUTO.COLL_DACOS_STATUS.SERVICE_ID IS '전송번호';
COMMENT ON COLUMN AUTO.COLL_DACOS_STATUS.PROC_ST IS '처리상태코드';
COMMENT ON COLUMN AUTO.COLL_DACOS_STATUS.PROC_TX IS '처리상태메시지';
COMMENT ON COLUMN AUTO.COLL_DACOS_STATUS.REG_DATE IS '등록일시';
COMMENT ON COLUMN AUTO.COLL_DACOS_STATUS.EULBU_NO IS '근저당 을부번호';

