"""
Oracle DDL Generator

Generates Oracle-compatible DDL statements from ERD models.
"""

from typing import List
from ..models.diagram import Diagram
from ..models.table import Table
from ..models.column import Column
from ..models.relationship import Relationship


class OracleDDLGenerator:
    """Generator for Oracle DDL statements"""

    def __init__(self, diagram: Diagram):
        """
        Initialize the generator with a diagram.

        Args:
            diagram: Diagram object to generate DDL from
        """
        self.diagram = diagram
        self.type_mappings = {
            'string': 'VARCHAR2',
            'text': 'CLOB',
            'integer': 'NUMBER',
            'bigint': 'NUMBER',
            'decimal': 'NUMBER',
            'boolean': 'NUMBER',
            'date': 'DATE',
            'datetime': 'TIMESTAMP',
            'timestamp': 'TIMESTAMP',
            'json': 'CLOB',
        }

    def generate(self) -> str:
        """
        Generate complete DDL for the entire diagram.

        Returns:
            Oracle DDL string
        """
        ddl_parts = []

        # Header
        ddl_parts.append(self._generate_header())

        # Drop tables (in reverse order to handle FK dependencies)
        ddl_parts.append(self._generate_drop_statements())

        # Create tables
        for table in self.diagram.tables:
            ddl_parts.append(self._generate_table_ddl(table))

        # Add foreign keys (separate ALTER statements)
        ddl_parts.append(self._generate_foreign_keys())

        # Create sequences for auto-increment columns
        ddl_parts.append(self._generate_sequences())

        # Create triggers for auto-increment
        ddl_parts.append(self._generate_triggers())

        return "\n\n".join(filter(None, ddl_parts))

    def _generate_header(self) -> str:
        """Generate DDL header with metadata"""
        header = f"""-- ================================================
-- Oracle DDL Generated by Python ERD Tool
-- Diagram: {self.diagram.name}
-- Version: {self.diagram.version}
-- Generated: {self.diagram.updated_at.strftime('%Y-%m-%d %H:%M:%S')}
-- ================================================
"""
        return header

    def _generate_drop_statements(self) -> str:
        """Generate DROP TABLE statements"""
        if not self.diagram.tables:
            return ""

        drops = ["-- Drop existing tables"]

        # Drop sequences first
        for table in self.diagram.tables:
            for column in table.columns:
                if column.auto_increment:
                    seq_name = f"SEQ_{table.physical_name}_{column.physical_name}"
                    drops.append(f"DROP SEQUENCE {seq_name};")

        # Drop tables
        for table in reversed(self.diagram.tables):
            drops.append(f"DROP TABLE {table.physical_name} CASCADE CONSTRAINTS;")

        return "\n".join(drops)

    def _generate_table_ddl(self, table: Table) -> str:
        """
        Generate CREATE TABLE statement for a single table.

        Args:
            table: Table object

        Returns:
            CREATE TABLE DDL
        """
        lines = []

        # Table comment
        if table.comment:
            lines.append(f"-- {table.comment}")
        if table.logical_name:
            lines.append(f"-- {table.logical_name}")

        # CREATE TABLE
        lines.append(f"CREATE TABLE {table.physical_name} (")

        # Columns
        column_lines = []
        for column in table.columns:
            column_lines.append("  " + self._generate_column_definition(column))

        # Primary key
        pk_columns = table.get_primary_keys()
        if pk_columns:
            pk_names = ", ".join(f"{col.physical_name}" for col in pk_columns)
            pk_constraint_name = f"PK_{table.physical_name}"
            column_lines.append(f"  CONSTRAINT {pk_constraint_name} PRIMARY KEY ({pk_names})")

        # Unique constraints
        unique_columns = [col for col in table.columns if col.unique and not col.primary_key]
        for col in unique_columns:
            uk_name = f"UK_{table.physical_name}_{col.physical_name}"
            column_lines.append(f"  CONSTRAINT {uk_name} UNIQUE ({col.physical_name})")

        lines.append(",\n".join(column_lines))
        lines.append(");")

        # Add table comment
        if table.comment:
            escaped_comment = table.comment.replace("'", "''")
            lines.append(f"COMMENT ON TABLE {table.physical_name} IS '{escaped_comment}';")

        # Add column comments
        for column in table.columns:
            if column.comment:
                escaped_comment = column.comment.replace("'", "''")
                lines.append(f"COMMENT ON COLUMN {table.physical_name}.{column.physical_name} IS '{escaped_comment}';")
            elif column.logical_name:
                escaped_logical = column.logical_name.replace("'", "''")
                lines.append(f"COMMENT ON COLUMN {table.physical_name}.{column.physical_name} IS '{escaped_logical}';")

        return "\n".join(lines)

    def _generate_column_definition(self, column: Column) -> str:
        """
        Generate column definition.

        Args:
            column: Column object

        Returns:
            Column definition string
        """
        parts = [column.physical_name]

        # Data type (Oracle doesn't have auto_increment in column def)
        oracle_type = self._map_data_type(column)
        parts.append(oracle_type)

        # DEFAULT value
        if column.default_value is not None and not column.auto_increment:
            if isinstance(column.default_value, str):
                escaped_default = column.default_value.replace("'", "''")
                parts.append(f"DEFAULT '{escaped_default}'")
            elif isinstance(column.default_value, bool):
                parts.append(f"DEFAULT {1 if column.default_value else 0}")
            else:
                parts.append(f"DEFAULT {column.default_value}")

        # NULL/NOT NULL
        if not column.nullable:
            parts.append("NOT NULL")

        return " ".join(parts)

    def _map_data_type(self, column: Column) -> str:
        """
        Map abstract data type to Oracle type.

        Args:
            column: Column object

        Returns:
            Oracle data type string
        """
        base_type = self.type_mappings.get(column.data_type, column.data_type.upper())

        # Handle length/precision
        if base_type == 'VARCHAR2':
            if column.length is not None:
                return f"VARCHAR2({column.length})"
            else:
                return "VARCHAR2(255)"
        elif base_type == 'NUMBER':
            if column.data_type == 'boolean':
                return "NUMBER(1)"
            elif column.precision is not None:
                if column.scale is not None:
                    return f"NUMBER({column.precision},{column.scale})"
                else:
                    return f"NUMBER({column.precision})"
            elif column.data_type in ['integer', 'bigint']:
                return "NUMBER(19)"  # Default for integers
            else:
                return "NUMBER"
        else:
            return base_type

    def _generate_foreign_keys(self) -> str:
        """
        Generate ALTER TABLE statements to add foreign keys.

        Returns:
            Foreign key DDL
        """
        if not self.diagram.relationships:
            return ""

        fk_statements = ["-- Add foreign key constraints"]

        for relationship in self.diagram.relationships:
            # Skip many-to-many (would need junction table)
            if relationship.is_many_to_many():
                fk_statements.append(
                    f"-- Skipping N:N relationship: {relationship.source_table_id} <-> {relationship.target_table_id}"
                )
                continue

            # Get table objects
            source_table = self.diagram.get_table(relationship.source_table_id)
            target_table = self.diagram.get_table(relationship.target_table_id)

            if not source_table or not target_table:
                continue

            # Get column names
            source_cols = []
            for col_id in relationship.source_column_ids:
                col = source_table.get_column(col_id)
                if col:
                    source_cols.append(col.physical_name)

            target_cols = []
            for col_id in relationship.target_column_ids:
                col = target_table.get_column(col_id)
                if col:
                    target_cols.append(col.physical_name)

            if not source_cols or not target_cols:
                continue

            # Generate FK name
            fk_name = f"FK_{target_table.physical_name}_{source_table.physical_name}"
            if len(fk_name) > 30:  # Oracle limit
                fk_name = f"FK_{target_table.physical_name[:10]}_{source_table.physical_name[:10]}"

            # Build ALTER TABLE statement
            source_cols_str = ", ".join(source_cols)
            target_cols_str = ", ".join(target_cols)

            fk_statement = f"""ALTER TABLE {target_table.physical_name}
  ADD CONSTRAINT {fk_name}
  FOREIGN KEY ({target_cols_str})
  REFERENCES {source_table.physical_name} ({source_cols_str})"""

            # Add referential actions
            if relationship.on_delete == "CASCADE":
                fk_statement += "\n  ON DELETE CASCADE"
            elif relationship.on_delete == "SET NULL":
                fk_statement += "\n  ON DELETE SET NULL"

            fk_statement += ";"

            fk_statements.append(fk_statement)

        return "\n\n".join(fk_statements)

    def _generate_sequences(self) -> str:
        """
        Generate sequence creation statements for auto-increment columns.

        Returns:
            Sequence DDL
        """
        sequences = ["-- Create sequences for auto-increment columns"]
        has_sequences = False

        for table in self.diagram.tables:
            for column in table.columns:
                if column.auto_increment:
                    seq_name = f"SEQ_{table.physical_name}_{column.physical_name}"
                    sequences.append(f"CREATE SEQUENCE {seq_name} START WITH 1 INCREMENT BY 1;")
                    has_sequences = True

        return "\n".join(sequences) if has_sequences else ""

    def _generate_triggers(self) -> str:
        """
        Generate triggers for auto-increment columns.

        Returns:
            Trigger DDL
        """
        triggers = ["-- Create triggers for auto-increment columns"]
        has_triggers = False

        for table in self.diagram.tables:
            for column in table.columns:
                if column.auto_increment:
                    seq_name = f"SEQ_{table.physical_name}_{column.physical_name}"
                    trigger_name = f"TRG_{table.physical_name}_{column.physical_name}"

                    trigger = f"""CREATE OR REPLACE TRIGGER {trigger_name}
BEFORE INSERT ON {table.physical_name}
FOR EACH ROW
BEGIN
  IF :NEW.{column.physical_name} IS NULL THEN
    SELECT {seq_name}.NEXTVAL INTO :NEW.{column.physical_name} FROM DUAL;
  END IF;
END;
/"""
                    triggers.append(trigger)
                    has_triggers = True

        return "\n\n".join(triggers) if has_triggers else ""

    def generate_table_ddl(self, table_id: str) -> str:
        """
        Generate DDL for a single table.

        Args:
            table_id: ID of the table

        Returns:
            DDL string or empty if table not found
        """
        table = self.diagram.get_table(table_id)
        if not table:
            return ""

        return self._generate_table_ddl(table)
