"""
PostgreSQL DDL Generator

Generates PostgreSQL-compatible DDL statements from ERD models.
"""

from typing import List
from ..models.diagram import Diagram
from ..models.table import Table
from ..models.column import Column
from ..models.relationship import Relationship
from config import DATA_TYPE_MAPPINGS


class PostgreSQLDDLGenerator:
    """Generator for PostgreSQL DDL statements"""

    def __init__(self, diagram: Diagram):
        """
        Initialize the generator with a diagram.

        Args:
            diagram: Diagram object to generate DDL from
        """
        self.diagram = diagram
        self.type_mappings = DATA_TYPE_MAPPINGS.get('postgresql', {})

    def generate(self) -> str:
        """
        Generate complete DDL for the entire diagram.

        Returns:
            PostgreSQL DDL string
        """
        ddl_parts = []

        # Header
        ddl_parts.append(self._generate_header())

        # Drop tables (in reverse order to handle FK dependencies)
        ddl_parts.append(self._generate_drop_statements())

        # Create tables
        for table in self.diagram.tables:
            ddl_parts.append(self._generate_table_ddl(table))

        # Add foreign keys (separate ALTER statements)
        ddl_parts.append(self._generate_foreign_keys())

        # Create sequences for auto-increment columns
        ddl_parts.append(self._generate_sequences())

        return "\n\n".join(filter(None, ddl_parts))

    def _generate_header(self) -> str:
        """Generate DDL header with metadata"""
        header = f"""-- ================================================
-- PostgreSQL DDL Generated by Python ERD Tool
-- Diagram: {self.diagram.name}
-- Version: {self.diagram.version}
-- Generated: {self.diagram.updated_at.strftime('%Y-%m-%d %H:%M:%S')}
-- ================================================

-- Drop existing tables
"""
        return header

    def _generate_drop_statements(self) -> str:
        """Generate DROP TABLE statements"""
        if not self.diagram.tables:
            return ""

        drops = []
        for table in reversed(self.diagram.tables):
            drops.append(f"DROP TABLE IF EXISTS {table.physical_name} CASCADE;")

        return "\n".join(drops)

    def _generate_table_ddl(self, table: Table) -> str:
        """
        Generate CREATE TABLE statement for a single table.

        Args:
            table: Table object

        Returns:
            CREATE TABLE DDL
        """
        lines = []

        # Table comment
        if table.comment:
            lines.append(f"-- {table.comment}")
        if table.logical_name:
            lines.append(f"-- {table.logical_name}")

        # CREATE TABLE
        lines.append(f"CREATE TABLE {table.physical_name} (")

        # Columns
        column_lines = []
        for column in table.columns:
            column_lines.append("  " + self._generate_column_definition(column))

        # Primary key
        pk_columns = table.get_primary_keys()
        if pk_columns:
            pk_names = ", ".join(f"{col.physical_name}" for col in pk_columns)
            column_lines.append(f"  PRIMARY KEY ({pk_names})")

        # Unique constraints
        unique_columns = [col for col in table.columns if col.unique and not col.primary_key]
        for col in unique_columns:
            column_lines.append(f"  UNIQUE ({col.physical_name})")

        lines.append(",\n".join(column_lines))
        lines.append(");")

        # Add table comment
        if table.comment:
            escaped_comment = table.comment.replace("'", "''")
            lines.append(f"COMMENT ON TABLE {table.physical_name} IS '{escaped_comment}';")

        # Add column comments
        for column in table.columns:
            if column.comment:
                escaped_comment = column.comment.replace("'", "''")
                lines.append(f"COMMENT ON COLUMN {table.physical_name}.{column.physical_name} IS '{escaped_comment}';")
            elif column.logical_name:
                escaped_logical = column.logical_name.replace("'", "''")
                lines.append(f"COMMENT ON COLUMN {table.physical_name}.{column.physical_name} IS '{escaped_logical}';")

        return "\n".join(lines)

    def _generate_column_definition(self, column: Column) -> str:
        """
        Generate column definition.

        Args:
            column: Column object

        Returns:
            Column definition string
        """
        parts = [column.physical_name]

        # Data type
        pg_type = self._map_data_type(column)
        parts.append(pg_type)

        # DEFAULT value
        if column.default_value is not None and not column.auto_increment:
            if isinstance(column.default_value, str):
                escaped_default = column.default_value.replace("'", "''")
                parts.append(f"DEFAULT '{escaped_default}'")
            elif isinstance(column.default_value, bool):
                parts.append(f"DEFAULT {str(column.default_value).upper()}")
            else:
                parts.append(f"DEFAULT {column.default_value}")

        # NULL/NOT NULL
        if not column.nullable:
            parts.append("NOT NULL")

        return " ".join(parts)

    def _map_data_type(self, column: Column) -> str:
        """
        Map abstract data type to PostgreSQL type.

        Args:
            column: Column object

        Returns:
            PostgreSQL data type string
        """
        base_type = self.type_mappings.get(column.data_type, column.data_type.upper())

        # Handle auto-increment
        if column.auto_increment:
            if base_type in ['INTEGER', 'INT']:
                return 'SERIAL'
            elif base_type == 'BIGINT':
                return 'BIGSERIAL'

        # Handle length/precision
        if column.length is not None and base_type == 'VARCHAR':
            return f"VARCHAR({column.length})"
        elif column.precision is not None:
            if column.scale is not None:
                return f"{base_type}({column.precision},{column.scale})"
            else:
                return f"{base_type}({column.precision})"
        else:
            # Default lengths for common types
            if base_type == "VARCHAR" and column.length is None:
                return "VARCHAR(255)"
            return base_type

    def _generate_foreign_keys(self) -> str:
        """
        Generate ALTER TABLE statements to add foreign keys.

        Returns:
            Foreign key DDL
        """
        if not self.diagram.relationships:
            return ""

        fk_statements = ["-- Add foreign key constraints"]

        for relationship in self.diagram.relationships:
            # Skip many-to-many (would need junction table)
            if relationship.is_many_to_many():
                fk_statements.append(
                    f"-- Skipping N:N relationship: {relationship.source_table_id} <-> {relationship.target_table_id}"
                )
                continue

            # Get table objects
            source_table = self.diagram.get_table(relationship.source_table_id)
            target_table = self.diagram.get_table(relationship.target_table_id)

            if not source_table or not target_table:
                continue

            # Get column names
            source_cols = []
            for col_id in relationship.source_column_ids:
                col = source_table.get_column(col_id)
                if col:
                    source_cols.append(col.physical_name)

            target_cols = []
            for col_id in relationship.target_column_ids:
                col = target_table.get_column(col_id)
                if col:
                    target_cols.append(col.physical_name)

            if not source_cols or not target_cols:
                continue

            # Generate FK name
            fk_name = relationship.get_fk_name(target_table.physical_name)

            # Build ALTER TABLE statement
            source_cols_str = ", ".join(source_cols)
            target_cols_str = ", ".join(target_cols)

            fk_statement = f"""ALTER TABLE {target_table.physical_name}
  ADD CONSTRAINT {fk_name}
  FOREIGN KEY ({target_cols_str})
  REFERENCES {source_table.physical_name} ({source_cols_str})"""

            # Add referential actions
            if relationship.on_delete != "NO ACTION":
                fk_statement += f"\n  ON DELETE {relationship.on_delete}"

            if relationship.on_update != "NO ACTION":
                fk_statement += f"\n  ON UPDATE {relationship.on_update}"

            fk_statement += ";"

            fk_statements.append(fk_statement)

        return "\n\n".join(fk_statements)

    def _generate_sequences(self) -> str:
        """
        Generate sequence creation statements (if needed).

        Returns:
            Sequence DDL
        """
        # PostgreSQL SERIAL handles this automatically
        return ""

    def generate_table_ddl(self, table_id: str) -> str:
        """
        Generate DDL for a single table.

        Args:
            table_id: ID of the table

        Returns:
            DDL string or empty if table not found
        """
        table = self.diagram.get_table(table_id)
        if not table:
            return ""

        return self._generate_table_ddl(table)
